/* NEO_SKILL_META
{
  "name": "project_scaffold",
  "description": "Generates a folder structure and boilerplate for a given tech stack.",
  "argsSchema": {
    "type": "object",
    "properties": {
      "stack": { "type": "string", "enum": ["node-ts", "python-flask", "static-web"] },
      "path": { "type": "string", "description": "Where to create the project" }
    },
    "required": ["stack", "path"]
  }
}
NEO_SKILL_META */

import fs from 'fs';
import path from 'path';

const TEMPLATES: Record<string, Record<string, string>> = {
  "node-ts": {
    "package.json": `{"name":"new-project","version":"1.0.0","scripts":{"start":"tsx src/index.ts"},"dependencies":{"tsx":"latest"}}`,
    "src/index.ts": `console.log("Hello World");`,
    "README.md": `# Node/TS Project\nGenerated by Neo.`
  },
  "python-flask": {
    "requirements.txt": `flask\npython-dotenv`,
    "app.py": `from flask import Flask\napp = Flask(__name__)\n@app.route('/')\ndef hello(): return "Hello World"`,
    "README.md": `# Flask App\nGenerated by Neo.`
  },
  "static-web": {
    "index.html": `<!DOCTYPE html><html><body><h1>Hello World</h1></body></html>`,
    "style.css": `body { font-family: sans-serif; }`,
    "script.js": `console.log('Loaded');`
  }
};

export async function run(args: { stack: string; path: string }) {
  const root = path.resolve(process.cwd(), args.path);
  const template = TEMPLATES[args.stack];

  if (!template) return `Error: Stack '${args.stack}' not supported.`;
  if (!fs.existsSync(root)) fs.mkdirSync(root, { recursive: true });

  for (const [filepath, content] of Object.entries(template)) {
    const fullPath = path.join(root, filepath);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(fullPath, content);
  }

  return `✅ Scaffolding complete for ${args.stack} at ${root}`;
}